---
 - hosts: all
   user: root
   tasks:
     - name: Install git, Maven
       ansible.builtin.yum:
         name: "{{ packages }}"
         state: present
         update_cache: yes
       vars:
         packages:
           - maven
           - git
